# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blackLearning's blog
email: fuyigekua@foxmail.com
description: 前端学习的那些事儿
baseurl:  # the subpath of your site, e.g. /blog
github_username:  blackLearning
# Build settings
markdown: kramdown
encoding: utf-8
paginate: 4
gems: [jekyll-paginate]
paginate_path: "page:num"
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: false
config:
  js_dir:
  img_dir:
  css_dir:
